### ISSUE TITLE
realpath not installed when running on travis

### ISSUE THREAD

**Issue by kokarez** [facebook/ds2#181]
On the last [build] log:

```bash
/home/travis/build/facebook/ds2/Support/Scripts/common.sh: line 49: realpath: command not found
/home/travis/build/facebook/ds2/Support/Scripts/common.sh: line 49: realpath: command not found
```

I've randomly pick 3 others build and found the same error.

[build]: https://travis-ci.org/facebook/ds2/jobs/109791089

**Comment by sas** [comment]
We don't rely on the system `realpath` anymore so this shouldn't be an issue.
