### ISSUE TITLE
Add macosx Travis build for ds2

### ISSUE THREAD

**Issue by fjricci** [facebook/ds2#207]
It would be great if we could look into adding a mac build to Travis for now (even if we don't run any tests yet), just to test the stability of compilation, etc, as we start adding functionality for osx to ds2.

Eventually, we could hope to also run the full lldb test suite on mac.

https://docs.travis-ci.com/user/osx-ci-environment/

**Comment by sas** [comment]
Yep. @kokarez said he'd look into it after we're done committing his huge
Darwin branch.

On Tuesday, March 1, 2016, Francis Ricci <notifications@github.com> wrote:

> It would be great if we could look into adding a mac build to Travis for
> now (even if we don't run any tests yet), just to test the stability of
> compilation, etc, as we start adding functionality for osx to ds2.
>
> Eventually, we could hope to also run the full lldb test suite on mac.
>
> https://docs.travis-ci.com/user/osx-ci-environment/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/ds2/issues/207>.
>


-- 
Stephane Sezer

**Comment by fjricci** [comment]
Awesome. :) Apparently you can't assign an issue to someone from outside Facebook, but I'll leave this here anyway

**Comment by kokarez** [comment]
osx builds are running on this PR:
https://github.com/facebook/ds2/pull/197

**Comment by sas** [comment]
@kokarez fixed this.
