### ISSUE TITLE
Support read-only hardware watchpoints on x86

### ISSUE THREAD

**Issue by fjricci** [facebook/ds2#257]
x86 hardware does not support read-only watchpoints natively. One solution is to set a read-write watchpoint, and then manually monitor the value of the memory location. If the value does not change (and was therefore only read from), trigger the watchpoint, otherwise ignore.

See a brief discussion here with regard to the gdb implementation:
https://www.sourceware.org/ml/gdb/2005-11/msg00231.html

**Comment by fjricci** [comment]
As a temporary work-around, we set a read-write watchpoint and print a warning when asked to set a read-only watchpoint.

**Comment by AndrewSB** [comment]
In progress at #510

**Comment by AndrewSB** [comment]
😿

**Comment by lanza** [comment]
#m thancc
