### ISSUE TITLE
Timeout of 45min for LLDB test on travis

### ISSUE THREAD

**Issue by kokarez** [facebook/ds2#326]
```sh
export LLDB_TEST_TIMEOUT=45m
```

I believe 45m is for each test, not the full suite. The timeout is given by dosep to dotest, and it's always 45m.

**Comment by sas** [comment]
Also 45 minutes is more than what travis allows anyway, so even if it's for the full suite it's probably too high.

**Comment by fjricci** [comment]
This is removed in the 3.8 suite patch.

But also, I think this is for each dotest run (so each file in the suite). TestLldbGdbServer was flaky with the default 10 minute timeout, so I arbitrarily bumped it up to 45. We can change to another value.

**Comment by sas** [comment]
Yeah putting it to 20 or something might make sense. Worse case we can run
some of our scripts with `travis_wait` to bump up the maximum timeout there
too.

On Mon, May 9, 2016 at 3:39 PM, Francis Ricci <notifications@github.com>
wrote:

> This is removed in the 3.8 suite patch.
>
> But also, I think this is for each dotest run (so each file in the suite).
> TestLldbGdbServer was flaky with the default 10 minute timeout, so I
> arbitrarily bumped it up to 45. We can change to another value.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/ds2/issues/326#issuecomment-218010982>
>



-- 
Stephane Sezer

**Comment by sas** [comment]
PR#342 deals with this.

**Comment by sas** [comment]
Merged.
