### ISSUE TITLE
qXfer:features:read does not work.

### ISSUE THREAD

**Issue by sas** [facebook/ds2#41]
qXfer:features:read seems buggy in ds2. When lldb requests register sets through this command, it doesn't seem to be able to properly read them afterwards.

This feature is disabled for now and lldb is able to query the list of registers by other mechanisms, which means debugging works fine. We should still fix this, as the qXfer based method is more efficient and uses a much smaller number of packets between server and client to achieve the same result.

To re-enable qXfer:features:read, look at Sources/GDBRemote/DebugSessionImpl.cpp:106 in the `#if notyet` block.

**Comment by sas** [comment]
This is taken care of by PR#90, correct?

**Comment by fjricci** [comment]
Yep

**Comment by fjricci** [comment]
Closed by PR#90
